# Generated by Django 4.1.5 on 2023-01-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
